---
- name: Dynaconf Configuration Management
  hosts: localhost
  become: false
  gather_facts: true

  vars:
    python_run_cmd: "python env.py"
    dynaconf_list_cmd: "dynaconf --instance config.settings list -k env"
    path_script: "python/"

  tasks:

    - name: Gathering facts
      ansible.builtin.debug:
        var: ansible_facts
      no_log: true

    - name: Dynaconf - Debug variables for default environment
      ansible.builtin.shell:
        cmd: |
          {{ dynaconf_list_cmd }}
          {{ python_run_cmd }}
        chdir: "{{ path_script }}"
      environment:
        SET_ENV: default
        MYAPP_DYNAMIC_ENV: sandbox

    # List development environment variables.
    # And run the configuration Python script.
    - name: Dynaconf - Debug variables for DEV environment
      ansible.builtin.shell:
        cmd: |
          {{ dynaconf_list_cmd }}
          {{ python_run_cmd }}
        chdir: "{{ path_script }}"
      register: command
      environment:
        SET_ENV: dev
        MYAPP_DYNAMIC_ENV: integration

    # This task will export the environment switcher.
    # List testing environment variables.
    # And run the configuration Python script.
    - name: Dynaconf - Debug variables for PRE environment
      ansible.builtin.shell:
        cmd: |
          export $SET_ENV
          {{ dynaconf_list_cmd }}
          {{ python_run_cmd }}
        chdir: "{{ path_script }}"
      environment:
        SET_ENV: pre
        MYAPP_DYNAMIC_ENV: preproduction

    # This task will export the environment switcher.
    # List production environment variables.
    # And run the configuration Python script.
    - name: Dynaconf - Debug variables for PRO environment
      ansible.builtin.shell:
        cmd: |
          export $SET_ENV
          {{ dynaconf_list_cmd }}
          {{ python_run_cmd }}
        chdir: "{{ path_script }}"
      environment:
        SET_ENV: pro
        MYAPP_DYNAMIC_ENV: production
