# Default settings variables

[default]
# Static ENV variable for DEFAULT deployment environment
ENV = "default"

[dev]
# Static ENV variable for DEV deployment environment
ENV = "int"

[pre]
# Static ENV variable for PRE deployment environment
ENV = "uat"

[pro]
# Static ENV variable for PRO deployment environment
ENV = "live"
